### ISSUE TITLE
Disable zip creation

### ISSUE THREAD

**Issue by harshithdwivedi** [imjsElectron/electron-differential-updater#29]
>When opening *.app (version) for first time, the module will make the zip of the app and move to cache location. For that time being autoUpdater.checkForUpdates() promise will throw the error saying Configuring update for differential download. Please try after some time

Is it possible to disable this zip creation?

I'm running my electron app on Apple M1 and I get the following error upon trying to run the app with this package: 

```
Error: Error: ENOENT: no such file or directory, mkdir '/Users/user/Library/Application Support/Caches/Electron'
    at /Users/manas/Desktop/AfterShoot-Source-Code/AfterShoot-Electron-Revamp/node_modules/@imjs/electron-differential-updater/src/prepareAppZip.ts:73:11
    at Object.<anonymous> (/Users/manas/Desktop/AfterShoot-Source-Code/AfterShoot-Electron-Revamp/node_modules/@imjs/electron-differential-updater/src/prepareAppZip.ts:12:1)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at doLoadAutoUpdater (/Users/manas/Desktop/AfterShoot-Source-Code/AfterShoot-Electron-Revamp/node_modules/@imjs/electron-differential-updater/src/main.ts:37:3)
    at Object.get [as autoUpdater] (/Users/manas/Desktop/AfterShoot-Source-Code/AfterShoot-Electron-Revamp/node_modules/@imjs/electron-differential-updater/src/main.ts:44:28)
    at Module.eval (webpack-internal:///./index.ts:55:66)
    at eval (webpack-internal:///./index.ts:459:30)
    at Module../index.ts (/Users/manas/Desktop/AfterShoot-Source-Code/AfterShoot-Electron-Revamp/dist/main/main.js:925:1)
    at __webpack_require__ (/Users/manas/Desktop/AfterShoot-Source-Code/AfterShoot-Electron-Revamp/dist/main/main.js:773:30)
    at fn (/Users/manas/Desktop/AfterShoot-Source-Code/AfterShoot-Electron-Revamp/dist/main/main.js:78:20)
    at Object.0 (/Users/manas/Desktop/AfterShoot-Source-Code/AfterShoot-Electron-Revamp/dist/main/main.js:1033:18)
    at __webpack_require__ (/Users/manas/Desktop/AfterShoot-Source-Code/AfterShoot-Electron-Revamp/dist/main/main.js:773:30)
    at /Users/manas/Desktop/AfterShoot-Source-Code/AfterShoot-Electron-Revamp/dist/main/main.js:888:37
    at Object.<anonymous> (/Users/manas/Desktop/AfterShoot-Source-Code/AfterShoot-Electron-Revamp/dist/main/main.js:891:10)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
```

I checked the contents of my `Users/user/Library/Application Support/` directory and it doesn't have the Caches folder in there.
Either the Electron folder in there should be created recursively along with the parent directory if needed or there should be an option to disable it.

@harshitsilly

**Comment by harshitsilly** [comment]
@harshithdwivedi  - please try version 5.1.4. Now the cache folder will be created if it doe not exist..
Will add an option to enable/disable differential update support fr mac..

**Comment by harshithdwivedi** [comment]
Wow, that was quick! Will try and report, thanks.
