### ISSUE TITLE
Mac differential update

### ISSUE THREAD

**Issue by toschlog** [imjsElectron/electron-differential-updater#32]
I'm confused about getting differential update to work on Mac.  Am I supposed to be calling generateZipandBlockmap() as part of my build process?  Like in "afterPack"?

Thanks for all your work.

**Comment by harshitsilly** [comment]
@toschlog : use generateZipandBlockmap() function after electron builder is done with the build Process.. 
like: `yarn dist && yarn generateZipandBlockmap`
Afterpack will not work as it is triggered before code sign.

**Comment by toschlog** [comment]
And now I'm confused about what files should be generated and uploaded.  I think I used to have:

app.dmg
app.dmg.blockmap
app-mac.zip

And now I also have:

app.zip

But I see an error in my log file that the auto-update system is looking for:

app-mac.zip.blockmap

What files should be created by the build and should they all get uploaded to my server?

Thanks.

**Comment by harshitsilly** [comment]
@toschlog  - this package only support .**zip** not a dmg.
Follow these steps:-
1) Make sure the electron builder has a target property which is set **zip**.
2) Run yarn dist && yarn generateZipandBlockmap.

Now you should have only 3 folder/files inside dist
1)Mac/
2)app-mac.zip
3)app-mac.zip.blockmap

If you are not getting these files.. than please share your builder configuration.
Note:- autoUpdate will look for this file  **app-mac.zip.blockmap**  to do differential download.
And yes this has to be uploaded to server.(This has been tested for only generic server configuration)
Sample - https://imjselectron.github.io/electron-differential-updater/#/?id=configure-publishing

**Comment by toschlog** [comment]
I messed up my generateZipandBlockmap call so it wasn't happening.  I'll fix it.

I have another question, though:

electron-builder -c.win.artifactName='${productName} Setup Dev.${ext}' -c.mac.artifactName='${productName}-${version}.${ext}'

**Comment by harshitsilly** [comment]
@toschlog - do you able to get the generateZipandBlockmap working?

**Comment by toschlog** [comment]
I was able to get generateZipandBlockmap and the differential update working.  Thanks for your help.

**Comment by Pulset** [comment]
> 2\. generateZipandBlockmap



> @toschlog - this package only support .**zip** not a dmg.
> Follow these steps:-
> 
> 1. Make sure the electron builder has a target property which is set tp only **zip**.
> 2. Run yarn dist && yarn generateZipandBlockmap.
> 
> Now you should have only 3 folder/files inside dist
> 1)Mac/
> 2)app-mac.zip
> 3)app-mac.zip.blockmap
> 
> If you are not getting these files.. than please share your builder configuration.
> 
> Note:- autoUpdate will look for this file **app-mac.zip.blockmap** to do differential download.
> And yes this has to be uploaded to server.(This has been tested for only generic server configuration)
> Sample - https://imjselectron.github.io/electron-differential-updater/#/?id=configure-publishing

I try differential update, it throw error xx.app/Contents/Resources/app/node_modules/react-dev-utils/node_modules/lodash/fp/assignIn.js: No such file or directory
ditto: Couldn't read pkzip signature.

**Comment by harshitsilly** [comment]
@Pulset - did you get the error during `generateZipandBlockmap` process.
and can you share the build configuration .. Are u doing asar thing?

**Comment by Pulset** [comment]
> @Pulset - did you get the error during `generateZipandBlockmap` process.
> and can you share the build configuration .. Are u doing asar thing?

@harshitsilly Yes, during generateZipandBlockmap process.I get error 
child_process.js:836
    throw err;
    ^

<ref *1> Error: spawnSync /bin/sh ENOBUFS
    at Object.spawnSync (internal/child_process.js:1074:20)
    at spawnSync (child_process.js:746:24)
    at execSync (child_process.js:828:15)
    at generateZipandBlockmap (/Users/zcy/Desktop/project/leo-gui/node_modules/@imjs/electron-differential-updater/out/generateZipandBlockmap.js:33:3)
    at Object.<anonymous> (/Users/zcy/Desktop/project/leo-gui/pack.js:13:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  errno: -55,
  code: 'ENOBUFS',
  syscall: 'spawnSync /bin/sh',
  path: '/bin/sh',
  spawnargs: [
    '-c',
    'ditto -V -c  -k --sequesterRsrc --keepParent "/Users/zcy/Desktop/project/leo-gui/dist/mac/敦煌.app" "/Users/zcy/Desktop/project/leo-gui/dist/敦煌-1.3.10-mac.zip"'
  ],
  error: [Circular *1],
  status: null,
  signal: 'SIGTERM',
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(1048640) [Uint8Array] [
       62,  62,  62,  32,  67, 111, 112, 121, 105, 110, 103,  32,
       47,  85, 115, 101, 114, 115,  47, 122,  99, 121,  47,  68,
      101, 115, 107, 116, 111, 112,  47, 112, 114, 111, 106, 101,
       99, 116,  47, 108, 101, 111,  45, 103, 117, 105,  47, 100,
      105, 115, 116,  47, 109,  97,  99,  47, 230, 149, 166, 231,
      133, 140,  46,  97, 112, 112,  32,  10,  99, 111, 112, 121,
      105, 110, 103,  32, 102, 105, 108, 101,  32,  46,  47, 230,
      149, 166, 231, 133, 140,  46,  97, 112, 112,  47,  67, 111,
      110, 116, 101, 110,
      ... 1048540 more items
    ]
  ],
  pid: 47123,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(1048640) [Uint8Array] [
     62,  62,  62,  32,  67, 111, 112, 121, 105, 110, 103,  32,
     47,  85, 115, 101, 114, 115,  47, 122,  99, 121,  47,  68,
    101, 115, 107, 116, 111, 112,  47, 112, 114, 111, 106, 101,
     99, 116,  47, 108, 101, 111,  45, 103, 117, 105,  47, 100,
    105, 115, 116,  47, 109,  97,  99,  47, 230, 149, 166, 231,
    133, 140,  46,  97, 112, 112,  32,  10,  99, 111, 112, 121,
    105, 110, 103,  32, 102, 105, 108, 101,  32,  46,  47, 230,
    149, 166, 231, 133, 140,  46,  97, 112, 112,  47,  67, 111,
    110, 116, 101, 110,
    ... 1048540 more items
  ]
}

Here is my configuration:
```js
"build": {
    "productName": "敦煌",
    "appId": "Leo",
    "copyright": "Copyright © 2019 ZooTeam",
    "asar": false,
    "electronDownload": {
      "mirror": "https://npm.taobao.org/mirrors/electron/"
    },
    "dmg": {
      "iconSize": 160,
      "contents": [
        {
          "x": 130,
          "y": 220
        },
        {
          "x": 410,
          "y": 220,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "mac": {
      "icon": "build/icons/mac/icon.png",
      "target": "zip"
    },
    "directories": {
      "output": "dist"
    },
    "publish": {
      "provider": "generic",
      "url": "http://127.0.0.1:7001/restapi/checkUpdate"
    },
    "files": []
  }
```

**Comment by Pulset** [comment]
@harshitsilly , I put { stdio: 'ignore' } or remove -V then build it. The output zip is too large,it's not differential size

**Comment by ArmelChesnais** [comment]
Removing `-V` did fix it for me, which was why I brought it up.
While it may not resolve issues with the resulting zip file being too large, it does fix issues with the console output overflowing the buffer, and should be implemented.

**Comment by harshitsilly** [comment]
@Pulset - can you confirm at what degree we are seeing the resultant zip size increase if we go ahead by removing -V.
I think it will not make much of the difference.

**Comment by ArmelChesnais** [comment]
-V is just for verbose logging to the terminal, and should have no effect on the actual zip file. Adding that flag should just be for printing each file name to the terminal as they get zipped up, not adding it simply doesn't print them to terminal as they get zipped up.
The issue for the -V flag is that the terminal output is being piped to a buffer, which has a hard limit, and will error out when that limit is passed.
Another alternative to maintain the -V flag would be to have the child process output inherit from the parent process, as it wouldn't require a buffer in that case.

**Comment by Pulset** [comment]
@harshitsilly I agree with ArmelChesnais.I confuse I can't differential update.I upload app.zip app.zip.blockmap and latest-mac.yml to the server. But it download full size rather than small size

**Comment by harshitsilly** [comment]
> @harshitsilly I agree with ArmelChesnais.I confuse I can't differential update.I upload app.zip app.zip.blockmap and latest-mac.yml to the server. But it download full size rather than small size
@Pulset in that case can u raise the issue with ur findings.

**Comment by Pulset** [comment]
@harshitsilly I want to konw  how you test differential update successfully

**Comment by ArmelChesnais** [comment]
@Pulset You'll want to post your logs, differential updater will log out details of the update. It would help to know if it's not able to do differential updating and falling back to full download, or if it can do differential updating, but ends up downloading everything by thinking that everything has changed.
Knowing what system you're on would help as well, and more info about your deployment (are you signing, notarizing, etc?).

**Comment by Pulset** [comment]
@harshitsilly , I get new error.
[2022-02-09 15:11:49.686] [info] Full: 118,714.94 KB, To download: 19,978.9 KB (17%)
[2022-02-09 15:11:49.813] [error] Cannot download differentially, fallback to full download: Error: Content-Type "multipart/byteranges" is expected, but got "application/zip"
    at ClientRequest.differentialDownloader.httpExecutor.createRequest.response (/Users/zcy/Desktop/project/dunHuang/leo-gui/dist/敦煌.app/Contents/Resources/app/node_modules/@imjs/electron-differential-updater/out/differentialDownloader/multipleRangeDownloader.js:124:14)
    at ClientRequest.emit (events.js:182:13)
    at URLRequest.ClientRequest.urlRequest.on (/Users/zcy/Desktop/project/dunHuang/leo-gui/dist/敦煌.app/Contents/Resources/electron.asar/browser/api/net.js:207:12)
    at URLRequest.emit (events.js:182:13)
